### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by captn3m0** [yankee101/HNDN#1]
1. I could probably publish the extension in your name
2. Move all files to the root directory
3. Directories with spaces are not good.

**Comment by tocttou** [comment]
1. Please publish it. Thanks.
2. Done.

**Comment by captn3m0** [comment]
[Published it](https://chrome.google.com/webstore/detail/hkfhkpdkpjnbijpgfndjdghboghcplnc/publish-delayed).

Whenever you want to do a new major release, let me know.

**Comment by captn3m0** [comment]
[Published it](https://chrome.google.com/webstore/detail/hkfhkpdkpjnbijpgfndjdghboghcplnc/publish-delayed).

Whenever you want to do a new major release, let me know.

**Comment by tocttou** [comment]
Thanks! :)
